name: zaojiangchong_project
description: Flutter windows开发论文写作助手，后期考虑移植mac、linux.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1  # 版本号管理

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  dio: ^3.0.10 # 网络请求库
  flutter_swiper: ^1.1.6 # 轮播图等组件
  url_launcher: ^5.7.2 # url发射器
  get: ^3.23.1 # GetX状态管理+路由管理+依赖管理
  shared_preferences: ^0.5.12 # flutter 持久化插件
  bitsdojo_window: ^0.0.3 # windows窗口控制
  win32: ^1.7.4 # win32接口
  package_info_plus: ^0.6.3 # 获取应用信息
  flutter_update_dialog: ^1.0.0 # 更新弹出框
  bot_toast: ^3.0.5 # 提示

  #  desktop_window: ^0.3.0 # window_size：屏幕尺寸插件
  # file_chooser：文件选择插件
  # kumi_popup_window: ^1.0.12： windows弹窗插件
  # flutter_menu：菜单栏设置
  # screenshot: 屏幕截图

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/bg_update_top.png
     - assets/images/app_logo.png
     - assets/images/app_logo_text.png
     - assets/images/decorative_figure.png
     - assets/images/logo_checkpass.png
     - assets/images/logo_jiangchong.png
     - assets/images/logo_turnitin.png
     - assets/images/logo_wanfang.png
     - assets/images/logo_weipu.png
     - assets/images/logo_zhiwang.png
     - assets/images/mini_logo_checkpass.png
     - assets/images/mini_logo_jiangchong.png
     - assets/images/mini_logo_turnitin.png
     - assets/images/mini_logo_wanfang.png
     - assets/images/mini_logo_weipu.png
     - assets/images/mini_logo_zhiwang.png
     - assets/images/search.png
     - assets/images/smart_yun.png
     - assets/images/vip_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#     - family: Muyao
#       fonts:
#         - asset: assets/fonts/Muyao-Softbrush.ttf
#     - family: SiyuanBold
#       fonts:
#         - asset: assets/fonts/SourceHanSansCN-Bold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
